version: "3.5"
services:
  db:
    image: postgres
    volumes:
      - pg-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_PASSWORD=${DEV_PASS}
    networks:
      - backend
  curriculum:
    build: .
    command: ./scripts/docker-entrypoint.sh
    volumes:
      - .:/app
      - node_modules:/app/node_modules # ensures we retain node_modules from docker build
    ports:
      - "1235:1234"
      - "3020:3000"
    depends_on:
      - db
    environment:
      - PROXY_URL=http://host.docker.internal:8888
      - RAILS_DEV_DB_PASS=${DEV_PASS}
      - OAUTH_DEBUG
      - ENV_TYPE=development
      - HOSTNAME_ENV
      - REDIS_URL=redis://redis:6379/0
    stdin_open: true
    tty: true # Allow interactive byebug sessions.
    networks:
      - teachcomputingorg_main
      - backend
  sidekiq:
    build: .
    command: bundle exec sidekiq
    networks:
      - backend
volumes:
  pg-data:
  node_modules:
networks:
  teachcomputingorg_main:
    external: true
  backend:
