services:
  docker-host:
    image: qoomon/docker-host
    cap_add: [ 'NET_ADMIN', 'NET_RAW' ]
    networks:
      default:
        aliases:
          - teachcomputing.test
          - teachcomputing.rpfdev.com
  db:
    image: postgres:15.5
    volumes:
      - pg-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_PASSWORD=${DEV_PASS}
    restart: unless-stopped
    env_file:
      - .env

  redis:
    image: "redis:alpine"
    command: redis-server --requirepass $REDIS_HOST_PASSWORD
    ports:
      - "6380:6379"
    restart: unless-stopped
    env_file:
      - .env

  sidekiq:
    build: .
    command: bundle exec sidekiq
    depends_on:
      - redis
      - docker-host
    volumes:
      - .:/app
      - bundle:/usr/local/bundle
    environment:
      - TC_API_URL=http://teachcomputing.rpfdev.com
      - TC_API_SECRET=secret
    restart: unless-stopped
    env_file:
      - .env

  curriculum:
    build: .
    command: ./scripts/docker-entrypoint.sh
    volumes:
      - .:/app
      - node_modules:/app/node_modules # ensures we retain node_modules from docker build
      - bundle:/usr/local/bundle
    ports:
      - "1236:1234"
      - "1237:1235"
      - "3020:3000"
    depends_on:
      - db
      - redis
      - sidekiq
      - docker-host
    environment:
      - PROXY_URL=http://host.docker.internal:8888
      - RAILS_DEV_DB_PASS=${DEV_PASS}
    env_file:
      - .env
    stdin_open: true
    tty: true # Allow interactive byebug sessions.
    restart: unless-stopped

volumes:
  bundle:
  pg-data:
  node_modules:
