version: '3.5'
services:
  db:
    image: postgres
    volumes:
      - pg-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=${DEV_PASS}
  web:
    build: .
    command: ./scripts/docker-entrypoint.sh
    volumes:
      - .:/app
      - node_modules:/app/node_modules # ensures we retain node_modules from docker build
    ports:
      - '1234:1234'
      - '3000:3000'
    depends_on:
      - db
    environment:
      - PROXY_URL=http://host.docker.internal:8888
      - RAILS_DEV_DB_PASS=${DEV_PASS}
      - OAUTH_DEBUG
      - ENV_TYPE=development
    stdin_open: true
    tty: true # Allow interactive byebug sessions.
volumes:
  pg-data:
  node_modules:
