version: 2.1

orbs:
  ruby: circleci/ruby@1

jobs:
  standardrb:
    docker:
      - image: "cimg/ruby:3.3.6"
    steps:
      - checkout
      - run:
          name: Set bundle without development
          command: bundle config set without "development"
      - ruby/install-deps
      - run:
          name: Inspecting code with standardrb
          command: bundle exec standardrb

  test:
    docker:
      - image: cimg/ruby:3.3.6-node
        environment:
          BUNDLE_JOBS: 3
          BUNDLE_RETRY: 3
          BUNDLE_PATH: vendor/bundle
          CREDENTIALS_ENV: test
          DB_HOST: 127.0.0.1
          PGHOST: 127.0.0.1
          PGUSER: ncce_test
          RAILS_ENV: test
      - image: cimg/postgres:15.5
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: ncce_test
          POSTGRES_PASSWORD: ""
    steps:
      - checkout
      - run:
          name: Set bundle without development
          command: bundle config set without "development"
      - ruby/install-deps

      - run:
          name: Yarn Install
          command: yarn install

      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m

      - run:
          name: Database setup
          command: bin/rails db:schema:load --trace

      - run:
          name: Run rspec
          command: |
            bundle exec rspec

      - run:
          name: Run brakeman
          command: |
            bundle exec brakeman -q -i config/brakeman.ignore --no-summary
      - store_artifacts:
          path: coverage

workflows:
  version: 2
  standardrb:
    jobs:
      - standardrb:
          filters:
            branches:
              ignore:
                - main

  build_and_test:
    jobs:
      - test

